# Generated by Django 5.0.1 on 2024-02-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_folder_name_alter_folder_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenthistory',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='h_folder', to='docs.folder'),
            preserve_default=False,
        ),
    ]
