# Generated by Django 5.0.1 on 2024-02-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentHistory',
        ),
    ]
